from openpyxl import Workbook
from openpyxl import load_workbook
import json

# Exercise 14.5 a

# Reading data from Excel and storing it in dictionary. print it in JSON format
workbook = load_workbook(filename="TestData.xlsx")
sheet = workbook.active

products = {}
for column in sheet.iter_cols( min_row=1, min_col=2,values_only=True):
    # the number in the [] is the row number starting at 0 in the excel.
    # the column number is generated by the loop counter starting from 3
    test_id = column[0]
    product = {
        "category": column[1],
        "product_id": column[2],
        "Quantity": column[3],
        "Color": column[4]
    }
    products[test_id] = product

print(json.dumps(products, indent=4))
